# Generated by Django 3.1 on 2020-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_directory', models.CharField(max_length=100)),
                ('draft_name', models.CharField(max_length=100)),
                ('draft_form_name', models.CharField(max_length=100)),
                ('inspection_title', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('stakeholders', models.CharField(max_length=100)),
                ('inspection_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('datetime', models.DateField(max_length=50)),
                ('status', models.IntegerField()),
                ('operating_area', models.CharField(max_length=100)),
                ('inspection_approve', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
