# Generated by Django 3.1 on 2020-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_safe_app', '0002_auto_20200821_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=100)),
                ('role_id', models.IntegerField()),
                ('zipcode', models.CharField(blank=True, max_length=100)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('user_directory', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inspections',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
