# Generated by Django 3.1 on 2020-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_safe_app', '0003_auto_20200822_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=100)),
            ],
        ),
    ]
