# Generated by Django 3.1 on 2020-08-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_safe_app', '0005_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
