# Generated by Django 3.1 on 2020-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_safe_app', '0007_inspections_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspections',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
