# Generated by Django 3.1 on 2020-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_safe_app', '0008_auto_20200903_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspections',
            name='datetime',
            field=models.DateField(blank=True, max_length=50),
        ),
    ]
